Create default module-level PastebinAPI instance
Symptom:

```
>>> Pastebin.paste(api_dev_key, paste_info)
TypeError: unbound method paste() must be called with PastebinAPI instance as first argument (got unicode instance instead)
```

Solution:

Create a default instance of PastebinAPI and set the module-level names to the methods of that instance, instead of using the unbound methods of the class.